import re
path = 'apps/api/src/main/java/com/cryptostrategy/platform/api/experiment/ExperimentRequestMapper.java'
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

# request.generator().generatorId().value() -> new GeneratorId(request.generator().generatorId().value())
# Actually, the error says: String cannot be converted to GeneratorId
# Wait, request.generator().generatorId() returns String if it was generated by OpenAPI.
# So we need to do new GeneratorId(...)
content = content.replace(
    'request.generator().generatorId().value()',
    'new com.cryptostrategy.platform.search.api.model.GeneratorId(request.generator().generatorId().value())'
)

# Wait, if generatorId() returns String directly, then .value() on String doesn't work!
# Let's check OpenAPI generator code or simply replace request.generator().generatorId().value() with new GeneratorId(request.generator().generatorId())
# If it's already a string, .value() might be invalid. Let's just do an aggressive replace.
content = re.sub(
    r'request\.generator\(\)\.generatorId\(\)(\.value\(\))?',
    r'new com.cryptostrategy.platform.search.api.model.GeneratorId(request.generator().generatorId())',
    content
)

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)
print("Fixed API Mapper")
