package com.cryptostrategy.platform.strategy.api.error;
public enum StrategyErrorCode { INVALID_PARAMETERS, INSUFFICIENT_DATA, STRATEGY_NOT_FOUND, STRATEGY_CONFLICT, DUPLICATE_REGISTRATION, UNSUPPORTED_VERSION, INTEGRITY_ERROR, STORAGE_UNAVAILABLE }
