package com.cryptostrategy.platform.backtesting.internal;
import static org.junit.jupiter.api.Assertions.*;
import com.cryptostrategy.platform.backtesting.api.model.*;import com.cryptostrategy.platform.domain.api.market.*;import com.cryptostrategy.platform.experiment.api.*;import com.cryptostrategy.platform.experiment.api.job.*;import com.cryptostrategy.platform.marketdata.api.model.*;import com.cryptostrategy.platform.strategy.api.Strategy;import com.cryptostrategy.platform.strategy.api.model.*;import java.math.BigDecimal;import java.time.Instant;import java.util.*;import org.junit.jupiter.api.Test;
class DeterministicBacktestEngineTest{
 @Test void executesDecisionAtNextOpenWithFeesAndBoundedBatches(){Fixture f=new Fixture();Strategy strategy=context->{StrategySignal signal=context.evaluationTime().equals(f.start.plusSeconds(60))?StrategySignal.BUY:context.evaluationTime().equals(f.start.plusSeconds(120))?StrategySignal.SELL:StrategySignal.HOLD;return new StrategyDecision(signal,context.evaluationTime(),f.reference,"TEST","test",Map.of());};var result=new DeterministicBacktestEngine().run(f.command(1),f.reader(),strategy);assertEquals(1,result.trades().size());assertEquals(f.start.plusSeconds(60),result.trades().getFirst().entryTime());assertEquals(f.start.plusSeconds(120),result.trades().getFirst().exitTime());assertEquals(3,result.equityCurveSummary().pointCount());assertTrue(result.finalCapital().value().signum()>0);}
 @Test void fingerprintDoesNotDependOnBatchSize(){Fixture f=new Fixture();Strategy hold=c->new StrategyDecision(StrategySignal.HOLD,c.evaluationTime(),f.reference,"HOLD","hold",Map.of());var a=new DeterministicBacktestEngine().run(f.command(1),f.reader(),hold);var b=new DeterministicBacktestEngine().run(f.command(3),f.reader(),hold);assertEquals(a.fingerprint(),b.fingerprint());assertEquals(a.equityCurveSummary().curveDigest(),b.equityCurveSummary().curveDigest());}
 @Test void reproductionComparesSemanticTradesRatherThanRuntimeIds(){Fixture f=new Fixture();Strategy strategy=context->{StrategySignal signal=context.evaluationTime().equals(f.start.plusSeconds(60))?StrategySignal.BUY:context.evaluationTime().equals(f.start.plusSeconds(120))?StrategySignal.SELL:StrategySignal.HOLD;return new StrategyDecision(signal,context.evaluationTime(),f.reference,"TEST","test",Map.of());};var original=new DeterministicBacktestEngine().run(f.command(1),f.reader(),strategy);var reproduced=new DeterministicBacktestEngine().run(f.command(3),f.reader(),strategy);var report=new BacktestReproductionVerifier().verify(original,reproduced);assertTrue(report.matched(),report.differences().toString());assertNotEquals(original.resultId(),reproduced.resultId());}
 private static final class Fixture{final Instant start=Instant.parse("2026-01-01T00:00:00Z");final DatasetVersionId datasetId=new DatasetVersionId("00000000000000000000000001");final TradingPair pair;final DatasetSnapshot dataset;final List<DatasetMembership> members;final StrategyReference reference=new StrategyReference(new StrategyVersionId("00000000000000000000000009"),new StrategyPluginId("test"),new SemanticVersion(1,0,0));Fixture(){Asset btc=new Asset(new AssetId("00000000000000000000000002"),new AssetSymbol("BTC"),Optional.empty(),true);Asset usdt=new Asset(new AssetId("00000000000000000000000003"),new AssetSymbol("USDT"),Optional.empty(),true);pair=new TradingPair(new TradingPairId("00000000000000000000000004"),btc,usdt,true);List<DatasetMembership> list=new ArrayList<>();for(int i=0;i<3;i++){Instant open=start.plusSeconds(i*60L);Candle c=new Candle(new CandleKey(MarketProvider.BINANCE,pair,Timeframe.ONE_MINUTE,open),open.plusSeconds(60),bd(100+i*10),bd(120+i*10),bd(90+i*10),bd(110+i*10),bd(1),true);list.add(new DatasetMembership(datasetId,i,new PersistedCandle(new CandleId(String.format("000000000000000000000000%02d",5+i)),c)));}members=List.copyOf(list);dataset=new DatasetSnapshot(datasetId,"1",MarketProvider.BINANCE,pair,Timeframe.ONE_MINUTE,"v1",start,start.plusSeconds(180),3,"sha256:"+"0".repeat(64),start);}
  ResolvedBacktestRun command(int batch){return new ResolvedBacktestRun(new ExperimentId("0000000000000000000000000A"),new CandidateId("0000000000000000000000000B"),new JobId("0000000000000000000000000C"),new AttemptId("0000000000000000000000000D"),dataset,new BacktestProvenance("manifest","dataset","strategy"),BacktestAssumptions.mvp(bd(1000),new BigDecimal("0.001"),new BigDecimal("0.001")),batch,1);}
  com.cryptostrategy.platform.marketdata.api.port.out.DatasetCandleReader reader(){return(id,from,size)->{int end=Math.min(from+size,members.size());return new CandleBatch(id,from,members.subList(from,end),end,end<members.size());};}
  static BigDecimal bd(long v){return BigDecimal.valueOf(v);}}
}
