package com.cryptostrategy.platform.backtesting.api.error;
public enum BacktestErrorCode { INVALID_DATASET, INVALID_BATCH, INVALID_CANDLE, CHECKSUM_MISMATCH, INVALID_STRATEGY, INVALID_ASSUMPTIONS, INVALID_LINEAGE, ATTEMPT_NOT_SUCCEEDED, DUPLICATE_OUTCOME, PERSISTENCE_CONFLICT }
