package com.cryptostrategy.platform.persistence.internal.strategy;
public final class StrategySql {
    private StrategySql(){}
    public static final String FIND_CATALOG="select strategy_version_id, fingerprint from strategy.strategy_version where plugin_id=? and version=?";
    public static final String INSERT_CATALOG="insert into strategy.strategy_version(strategy_version_id,plugin_id,version,display_name,parameter_schema,default_parameters,supported_signals,fingerprint) values (?,?,?,?,?::jsonb,?::jsonb,?::jsonb,?)";
    public static final String INSERT_ROOT="insert into strategy.user_strategy(user_strategy_id,owner_user_id,strategy_kind,name,description,status,created_at,updated_at) values (?,?,?,?,?,'ACTIVE',?,?)";
    public static final String INSERT_VERSION="insert into strategy.user_strategy_version(user_strategy_version_id,user_strategy_id,version_no,strategy_kind,strategy_version_id,parameters,policy_id,policy_version,policy_parameters,lifecycle_status,fingerprint,created_at) values (?,?,?,?,?,?::jsonb,?,?,?::jsonb,'DRAFT',?,?)";
    public static final String LIST_ROOTS="select user_strategy_id,strategy_kind,name,coalesce(description,'') as description,created_at from strategy.user_strategy where owner_user_id=? and status='ACTIVE' and (? is null or (created_at,user_strategy_id)<(select created_at,user_strategy_id from strategy.user_strategy where user_strategy_id=? and owner_user_id=?)) order by created_at desc,user_strategy_id desc limit ?";
    public static final String FIND_ROOT="select user_strategy_id,owner_user_id,strategy_kind,name,coalesce(description,'') as description,status,archived_at,created_at,updated_at from strategy.user_strategy where owner_user_id=? and user_strategy_id=?";
    public static final String FIND_VERSION="select v.user_strategy_version_id,v.user_strategy_id,v.version_no,v.strategy_kind,v.strategy_version_id,v.parameters::text,v.policy_id,v.policy_version,coalesce(v.policy_parameters,'{}'::jsonb)::text,v.lifecycle_status,v.fingerprint,v.published_at,v.created_at,sv.plugin_id,sv.version as plugin_version from strategy.user_strategy_version v join strategy.user_strategy s on s.user_strategy_id=v.user_strategy_id left join strategy.strategy_version sv on sv.strategy_version_id=v.strategy_version_id where s.owner_user_id=? and v.user_strategy_version_id=?";
    public static final String FIND_LATEST_VERSION="select v.user_strategy_version_id,v.user_strategy_id,v.version_no,v.strategy_kind,v.strategy_version_id,v.parameters::text,v.policy_id,v.policy_version,coalesce(v.policy_parameters,'{}'::jsonb)::text,v.lifecycle_status,v.fingerprint,v.published_at,v.created_at,sv.plugin_id,sv.version as plugin_version from strategy.user_strategy_version v join strategy.user_strategy s on s.user_strategy_id=v.user_strategy_id left join strategy.strategy_version sv on sv.strategy_version_id=v.strategy_version_id where s.owner_user_id=? and v.user_strategy_id=? order by v.version_no desc limit 1";
    public static final String LATEST_VERSION="select v.version_no from strategy.user_strategy_version v join strategy.user_strategy s on s.user_strategy_id=v.user_strategy_id where s.owner_user_id=? and v.user_strategy_id=? order by v.version_no desc limit 1 for update";
    public static final String PUBLISH="update strategy.user_strategy_version v set lifecycle_status='PUBLISHED',published_at=? from strategy.user_strategy s where v.user_strategy_id=s.user_strategy_id and s.owner_user_id=? and v.user_strategy_version_id=? and v.version_no=? and v.lifecycle_status='DRAFT'";
    public static final String ARCHIVE="update strategy.user_strategy set status='ARCHIVED',archived_at=?,updated_at=? where owner_user_id=? and user_strategy_id=? and status='ACTIVE'";
}
